name: Release Swift Package

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip Swift Package
        run: zip -r polkabind-swift-pkg.zip .

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Polkabind Swift Package ${{ github.ref_name }}"
          tag_name: ${{ github.ref_name }}
          files: polkabind-swift-pkg.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
